# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  # UI TEST (DEBUG)
  desc "AndroidTest Instrumentation"
      lane :ui_test do
        build_android_app(
          task: 'connected',
          build_type: 'Debug'
        )
  end

  desc "Build test apks (DEBUG)"
    lane :build do
      build_android_app(task: "clean")
      build_android_app(
        task: 'assemble',
        build_type: 'Debug'
      )
      build_android_app(
        task: 'assemble',
        build_type: 'AndroidTest'
      )
  end

  desc "Capture screenshots"
  lane :capture do
    screengrab
  end

  desc "Upload screenshots to Google Play Store"
  lane :upload_screenshots do
    upload_to_play_store(
      skip_upload_changelogs: true,
      skip_upload_aab: true,
      skip_upload_apk: true,
      changes_not_sent_for_review: true
    )
  end

  desc "Build release version"
  lane :release do
    build_android_app(task: "clean")
    build_android_app(
        task: 'bundle',
        build_type: 'Release',
        properties: {
             "android.injected.signing.store.file" => ENV['STORE_FILE'],
             "android.injected.signing.store.password" => ENV['STORE_PASSWORD'],
             "android.injected.signing.key.alias" => ENV['KEY_ALIAS'],
             "android.injected.signing.key.password" => ENV['KEY_PASSWORD'],
          }
    )
  end

  desc "Deploy a new version to the Google Play"
    lane :googleplay do
      upload_to_play_store(
          release_status: 'draft',
          track: 'production',
          aab: 'app/build/outputs/bundle/release/app-release.aab',
          skip_upload_screenshots: true,
          skip_upload_images: true
      )
    end
end
