# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Build debug and test APK"
  lane :build do
    build_android_app(task: "clean")
    build_android_app(
        task: 'assemble',
        build_type: 'Debug'
        )
    build_android_app(
        task: 'assemble',
        build_type: 'AndroidTest'
    )
  end

  desc "Capture screenshots"
  lane :capture do
    screengrab
  end

  desc "Runs all the tests"
  lane :test do
    build_android_app(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
